version: '3'
services:
  api-heroes-postgres:
    container_name: api-heroes-postgres
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: app:mysecretpassword@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: heroes
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - data:/var/lib/postgresql/data
volumes:
        data:
